### ISSUE TITLE
Integrate HGDB with Jython

### ISSUE THREAD

**Issue by ponyatov** [hypergraphdb/hypergraphdb#129]
I just started tiny project on using HGDB in Jython: https://github.com/ponyatov/pyhg

Need some samples if somebody uses Jython for (hyper)graph rewrite engine.

**Comment by ponyatov** [comment]
Now have some problem with org.hypergraphdb.atom.HGSubsumes vizibility in Jython:

`org.hypergraphdb.HGException: org.hypergraphdb.HGException: java.lang.RuntimeException: org.hypergraphdb.HGException: java.lang.ClassNotFoundException: org.hypergraphdb.atom.HGSubsumes`

**Comment by bolerio** [comment]
Re rewrite engine, please write to the Google Group - Peter Rowlands there is working on something similar. You two should talk and I can try to organize a meeting so we see if there is potential for collaboration.

Re that exception: this is a very fundamental class in HGDB, so it's some setup problem I believe. Can you tell me steps how to reproduce?

**Comment by ponyatov** [comment]
To reproduce problem you can git clone from https://github.com/ponyatov/pyhg
and just run make (it will install required .jars automatically)

**Comment by ponyatov** [comment]
With .jars from Seco distribution hgdb-1.4-snapshot got same error with je:
`org.hypergraphdb.HGException: org.hypergraphdb.HGException: java.lang.NoClassDefFoundError: com/sleepycat/je/DatabaseException`

Looks something wrong with dynamic class loading

**Comment by bolerio** [comment]
@ponyatov I clone and ran make on your project. It seems like it's open a HGDB instance correctly, but then you are closing while there is still an open transaction (see below). Should I assume your class loading/linking issues are resolved?

cd lib ; tar zx < hgdbdist-1.3-final.tar.gz
touch lib/hypergraphdb-1.3/readme.html
JYTHONPATH=lib/ply-3.10:lib/hypergraphdb-1.3/lib/hgdb-1.3.jar:lib/hypergraphdb-1.3/lib/hgbdbje-1.3.jar:lib/hypergraphdb-1.3/lib/je-5.0.34.jar java -cp lib/hypergraphdb-1.3/lib/hgdb-1.3.jar:lib/hypergraphdb-1.3/lib/hgbdbje-1.3.jar:lib/hypergraphdb-1.3/lib/je-5.0.34.jar -jar lib/jython-standalone-2.7.0.jar test.py
java.lang.IllegalStateException: There is 1 existing transaction opened against the Environment.
Aborting open transactions ...
aborting <Transaction id="14">
	at com.sleepycat.je.Environment.close(Environment.java:383)
	at org.hypergraphdb.storage.bje.BJEStorageImplementation.shutdown(BJEStorageImplementation.java:214)
	at org.hypergraphdb.HGStore.close(HGStore.java:382)
	at org.hypergraphdb.HyperGraph.open(HyperGraph.java:393)
	at org.hypergraphdb.HyperGraph.open(HyperGraph.java:211)
	at org.hypergraphdb.HyperGraph.<init>(HyperGraph.java:198)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:211)
	at org.python.core.PyReflectedConstructor.__call__(PyReflectedConstructor.java:180)
	at org.python.core.PyObject.__call__(PyObject.java:419)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.Deriveds.dispatch__init__(Deriveds.java:19)
	at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112)
	at org.python.core.PyType.type___call__(PyType.java:1713)
	at org.python.core.PyType.__call__(PyType.java:1696)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.pycode._pyx0.f$0(test.py:156)
	at org.python.pycode._pyx0.call_function(test.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
	at org.python.util.jython.run(jython.java:362)
	at org.python.util.jython.main(jython.java:142)
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    HyperGraph('db/test').close()
	at org.hypergraphdb.HyperGraph.open(HyperGraph.java:396)
	at org.hypergraphdb.HyperGraph.open(HyperGraph.java:211)
	at org.hypergraphdb.HyperGraph.<init>(HyperGraph.java:198)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:211)

org.hypergraphdb.HGException: org.hypergraphdb.HGException: java.lang.RuntimeException: org.hypergraphdb.HGException: java.lang.ClassNotFoundException: org.hypergraphdb.atom.HGSubsumes
make: *** [test.log] Error 255
