### ISSUE TITLE
Shutdown sometimes does not cause the JVM to exit.

### ISSUE THREAD

**Issue by hypergraphdb** [hypergraphdb/hypergraphdb#71]
Originally reported on Google Code with ID 72

```
What steps will reproduce the problem?
It sometimes occurs with Protege Plugins 0.9.8 release.

We expect the Process to shut down completely after user selects close.

Might be that we have parallel close calls.


```

Reported by `thomas.hilpold` on 2012-02-14 23:31:38

**Comment by brahmaiah123** [comment]
Hi  sir , 

I have also face same problem can you suggest me how to over ride this probelm , because almost 6 hours of time one job in hung state 

I am sending Thread Dump please find that

2017-05-02 04:02:33
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.74-b02 mixed mode):

"Attach Listener" #21 daemon prio=9 os_prio=0 tid=0x00007ff3e4001000 nid=0x501e waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Service Thread" #20 daemon prio=9 os_prio=0 tid=0x00007ff4e442c000 nid=0x211a runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C1 CompilerThread14" #19 daemon prio=9 os_prio=0 tid=0x00007ff4e4429000 nid=0x2118 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C1 CompilerThread13" #18 daemon prio=9 os_prio=0 tid=0x00007ff4e4426800 nid=0x2116 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C1 CompilerThread12" #17 daemon prio=9 os_prio=0 tid=0x00007ff4e4424800 nid=0x2115 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C1 CompilerThread11" #16 daemon prio=9 os_prio=0 tid=0x00007ff4e4422800 nid=0x2111 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C1 CompilerThread10" #15 daemon prio=9 os_prio=0 tid=0x00007ff4e4420000 nid=0x210c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread9" #14 daemon prio=9 os_prio=0 tid=0x00007ff4e441e000 nid=0x2108 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread8" #13 daemon prio=9 os_prio=0 tid=0x00007ff4e441c000 nid=0x2105 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread7" #12 daemon prio=9 os_prio=0 tid=0x00007ff4e441a000 nid=0x20fa waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread6" #11 daemon prio=9 os_prio=0 tid=0x00007ff4e4417800 nid=0x20f4 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread5" #10 daemon prio=9 os_prio=0 tid=0x00007ff4e4415800 nid=0x20f0 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread4" #9 daemon prio=9 os_prio=0 tid=0x00007ff4e4413800 nid=0x20ee waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread3" #8 daemon prio=9 os_prio=0 tid=0x00007ff4e4411000 nid=0x20ec waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread2" #7 daemon prio=9 os_prio=0 tid=0x00007ff4e440f000 nid=0x20ea waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007ff4e440d000 nid=0x20e9 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007ff4e440a000 nid=0x20e8 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007ff4e4408800 nid=0x20e7 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007ff4e43d5000 nid=0x20c9 in Object.wait() [0x00007ff48cccb000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000005c8208ee0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000005c8208ee0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

   Locked ownable synchronizers:
	- None

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007ff4e43d0800 nid=0x20c8 in Object.wait() [0x00007ff48cdcc000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000005c8206b50> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000005c8206b50> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

   Locked ownable synchronizers:
	- None

"main" #1 prio=5 os_prio=0 tid=0x00007ff4e400b800 nid=0x206c runnable [0x00007ff4eab82000]
   java.lang.Thread.State: RUNNABLE
	at org.springframework.asm.ClassReader.readField(ClassReader.java:718)
	at org.springframework.asm.ClassReader.accept(ClassReader.java:691)
	at org.springframework.asm.ClassReader.accept(ClassReader.java:508)
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:64)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:98)
	at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:102)
	- locked <0x00000005cd15e330> (a org.springframework.core.type.classreading.CachingMetadataReaderFactory$1)
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:279)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:248)
	at org.springframework.context.annotation.ComponentScanBeanDefinitionParser.parse(ComponentScanBeanDefinitionParser.java:87)
	at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:74)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1427)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1417)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:174)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:144)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:100)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:510)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:392)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:181)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:217)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:252)
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:127)
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:93)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:129)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:538)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:452)
	- locked <0x00000005ca9e8198> (a java.lang.Object)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.nissan.dbs.framework.common.JobStart.main(JobStart.java:57)

   Locked ownable synchronizers:
	- None

"VM Thread" os_prio=0 tid=0x00007ff4e43c9000 nid=0x20c4 runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007ff4e4021000 nid=0x206d runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007ff4e4022800 nid=0x206f runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00007ff4e4024800 nid=0x2070 runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00007ff4e4026800 nid=0x2071 runnable 

"GC task thread#4 (ParallelGC)" os_prio=0 tid=0x00007ff4e4028000 nid=0x2072 runnable 

"GC task thread#5 (ParallelGC)" os_prio=0 tid=0x00007ff4e402a000 nid=0x2073 runnable 

"GC task thread#6 (ParallelGC)" os_prio=0 tid=0x00007ff4e402c000 nid=0x2074 runnable 

"GC task thread#7 (ParallelGC)" os_prio=0 tid=0x00007ff4e402d800 nid=0x2075 runnable 

"GC task thread#8 (ParallelGC)" os_prio=0 tid=0x00007ff4e402f800 nid=0x2076 runnable 

"GC task thread#9 (ParallelGC)" os_prio=0 tid=0x00007ff4e4031800 nid=0x2078 runnable 

"GC task thread#10 (ParallelGC)" os_prio=0 tid=0x00007ff4e4033000 nid=0x2079 runnable 

"GC task thread#11 (ParallelGC)" os_prio=0 tid=0x00007ff4e4035000 nid=0x207a runnable 

"GC task thread#12 (ParallelGC)" os_prio=0 tid=0x00007ff4e4036800 nid=0x207b runnable 

"GC task thread#13 (ParallelGC)" os_prio=0 tid=0x00007ff4e4038800 nid=0x207c runnable 

"GC task thread#14 (ParallelGC)" os_prio=0 tid=0x00007ff4e403a800 nid=0x207e runnable 

"GC task thread#15 (ParallelGC)" os_prio=0 tid=0x00007ff4e403c000 nid=0x207f runnable 

"GC task thread#16 (ParallelGC)" os_prio=0 tid=0x00007ff4e403e000 nid=0x208f runnable 

"GC task thread#17 (ParallelGC)" os_prio=0 tid=0x00007ff4e4040000 nid=0x209c runnable 

"GC task thread#18 (ParallelGC)" os_prio=0 tid=0x00007ff4e4041800 nid=0x209d runnable 

"GC task thread#19 (ParallelGC)" os_prio=0 tid=0x00007ff4e4043800 nid=0x209f runnable 

"GC task thread#20 (ParallelGC)" os_prio=0 tid=0x00007ff4e4045800 nid=0x20a0 runnable 

"GC task thread#21 (ParallelGC)" os_prio=0 tid=0x00007ff4e4047000 nid=0x20a2 runnable 

"GC task thread#22 (ParallelGC)" os_prio=0 tid=0x00007ff4e4049000 nid=0x20a3 runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00007ff4e442f000 nid=0x211d waiting on condition 

JNI global references: 28

2017-05-02 04:02:44
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.74-b02 mixed mode):

"Attach Listener" #21 daemon prio=9 os_prio=0 tid=0x00007ff3e4001000 nid=0x501e waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Service Thread" #20 daemon prio=9 os_prio=0 tid=0x00007ff4e442c000 nid=0x211a runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C1 CompilerThread14" #19 daemon prio=9 os_prio=0 tid=0x00007ff4e4429000 nid=0x2118 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C1 CompilerThread13" #18 daemon prio=9 os_prio=0 tid=0x00007ff4e4426800 nid=0x2116 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C1 CompilerThread12" #17 daemon prio=9 os_prio=0 tid=0x00007ff4e4424800 nid=0x2115 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C1 CompilerThread11" #16 daemon prio=9 os_prio=0 tid=0x00007ff4e4422800 nid=0x2111 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C1 CompilerThread10" #15 daemon prio=9 os_prio=0 tid=0x00007ff4e4420000 nid=0x210c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread9" #14 daemon prio=9 os_prio=0 tid=0x00007ff4e441e000 nid=0x2108 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread8" #13 daemon prio=9 os_prio=0 tid=0x00007ff4e441c000 nid=0x2105 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread7" #12 daemon prio=9 os_prio=0 tid=0x00007ff4e441a000 nid=0x20fa waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread6" #11 daemon prio=9 os_prio=0 tid=0x00007ff4e4417800 nid=0x20f4 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread5" #10 daemon prio=9 os_prio=0 tid=0x00007ff4e4415800 nid=0x20f0 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread4" #9 daemon prio=9 os_prio=0 tid=0x00007ff4e4413800 nid=0x20ee waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread3" #8 daemon prio=9 os_prio=0 tid=0x00007ff4e4411000 nid=0x20ec waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread2" #7 daemon prio=9 os_prio=0 tid=0x00007ff4e440f000 nid=0x20ea waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007ff4e440d000 nid=0x20e9 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007ff4e440a000 nid=0x20e8 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007ff4e4408800 nid=0x20e7 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007ff4e43d5000 nid=0x20c9 in Object.wait() [0x00007ff48cccb000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000005c8208ee0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000005c8208ee0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

   Locked ownable synchronizers:
	- None

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007ff4e43d0800 nid=0x20c8 in Object.wait() [0x00007ff48cdcc000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000005c8206b50> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000005c8206b50> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

   Locked ownable synchronizers:
	- None

"main" #1 prio=5 os_prio=0 tid=0x00007ff4e400b800 nid=0x206c runnable [0x00007ff4eab82000]
   java.lang.Thread.State: RUNNABLE
	at org.springframework.asm.ClassReader.readField(ClassReader.java:718)
	at org.springframework.asm.ClassReader.accept(ClassReader.java:691)
	at org.springframework.asm.ClassReader.accept(ClassReader.java:508)
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:64)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:98)
	at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:102)
	- locked <0x00000005cd15e330> (a org.springframework.core.type.classreading.CachingMetadataReaderFactory$1)
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:279)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:248)
	at org.springframework.context.annotation.ComponentScanBeanDefinitionParser.parse(ComponentScanBeanDefinitionParser.java:87)
	at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:74)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1427)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1417)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:174)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:144)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:100)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:510)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:392)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:181)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:217)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:252)
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:127)
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:93)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:129)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:538)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:452)
	- locked <0x00000005ca9e8198> (a java.lang.Object)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.nissan.dbs.framework.common.JobStart.main(JobStart.java:57)

**Comment by bolerio** [comment]
Yes, I need to look into that pretty soon. Please ping me back in a week or two if it's still not fixed!

**Comment by brahmaiah123** [comment]
Hi sir ,

Please suggest me any solution like why it happens . Present also we are
checking but not found cause .


Thanks & Regards,
Brahmaiah K,
+91-9490206441

**Comment by bolerio** [comment]
@brahmaiah123 I look at your thread dump in detail and it doesn't appear to have any HyperGraphDB related code in it. If you just text search in the thread dump for the string 'hypergraphdb' which is in all HGDB package names, you won't find it. If there is a deadlock, it is due to some other part of your application.

**Comment by bolerio** [comment]
Ok, this original issue of the actual deadlock during close was still present in the latest, but is now fixed.
